# Generated by Django 3.1 on 2021-10-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='Product ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
        ),
    ]
