# Generated by Django 3.1 on 2021-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kes'), ('RWF', 'Rwf'), ('USD', 'Usd')], default='KES', max_length=5),
        ),
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Image Url'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
