# Generated by Django 3.1 on 2021-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211020_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='currency',
            field=models.CharField(choices=[('KES', 'KES'), ('RWF', 'KES'), ('USD', 'USD')], default='KES', max_length=5),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='product_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
