# Generated by Django 3.1 on 2022-01-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211113_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='currency',
            field=models.CharField(choices=[('KES', 'KES'), ('RWF', 'RWF'), ('USD', 'USD')], default='KES', max_length=5),
        ),
    ]
