# Generated by Django 3.1.11 on 2021-10-05 08:36

from django.db import migrations
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission

GROUPS = {
     'Sales Rep': {
        "payment": ["view"],
        "refund": ["view"],
        "payment log": ["view"],
        "refund log": ["view"],
    }
}


def create_sales_rep_group(apps, schema_editor):
    for group_name in GROUPS:
        new_group, _ = Group.objects.get_or_create(name=group_name)
        # Loop models in group
        for app_model in GROUPS[group_name]:

            # Loop permissions in group/model
            for permission_name in GROUPS[group_name][app_model]:

                # Generate permission name as Django would generate it
                name = "Can {} {}".format(permission_name, app_model)
                try:
                    model_add_perm = Permission.objects.get(name=name)
                except Permission.DoesNotExist:
                    continue

                new_group.permissions.add(model_add_perm)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sales_rep_group),
    ]
