# Generated by Django 3.1 on 2021-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_sales_rep_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_type',
            field=models.CharField(blank=True, choices=[('REG', 'REGULAR'), ('SRE', 'SALES REP')], default='REG', max_length=3, null=True, verbose_name='User Type'),
        ),
    ]
