# Generated by Django 3.1 on 2022-05-19 09:40

from django.db import migrations, models
import jaza_duka.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_user_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', jaza_duka.users.models.UserSoftDeleteManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='delete_user',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Delete this User'),
        ),
    ]
