# Generated by Django 3.1.9 on 2021-05-06 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('duka_id', models.IntegerField()),
                ('amount_auth', models.IntegerField()),
                ('currency', models.IntegerField(choices=[(1, 'Ksh'), (2, 'Rwf')], default=1)),
                ('date_auth', models.DateField()),
                ('amount_requested', models.IntegerField()),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(choices=[(1, 'Successful'), (2, 'Failed'), (3, 'Pending')], default=3)),
                ('cs_agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
