# Generated by Django 3.1.9 on 2021-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210506_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_auth',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
