# Generated by Django 3.1.9 on 2021-05-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210506_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_auth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='duka_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Successful'), (2, 'Failed'), (3, 'Pending')], default=3, null=True),
        ),
    ]
