# Generated by Django 3.1.9 on 2021-05-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210507_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pre_auth_verified',
            field=models.BooleanField(default=False),
        ),
    ]
