# Generated by Django 3.1.9 on 2021-05-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_pre_auth_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pre_auth_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Successful'), (2, 'Failed'), (3, 'Pending')], default=3, null=True),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_response', models.JSONField()),
                ('payment_status', models.CharField(max_length=30)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.payment')),
            ],
        ),
    ]
