# Generated by Django 3.1.9 on 2021-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20210511_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentlog',
            old_name='api_response',
            new_name='pre_auth_response',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='batch_id',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='request_response',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
