# Generated by Django 3.1.9 on 2021-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20210511_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='batch_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='request_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
