# Generated by Django 3.1.9 on 2021-05-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20210511_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('KES', 'Ksh'), ('RWF', 'Rwf')], default='KES', max_length=5),
        ),
    ]
