# Generated by Django 3.1.9 on 2021-05-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20210512_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pre_auth_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
