# Generated by Django 3.1.9 on 2021-05-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20210512_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date_auth',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
