# Generated by Django 3.1.11 on 2021-05-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='request_status',
            new_name='charge_confirmation_request_status',
        ),
        migrations.RenameField(
            model_name='paymentlog',
            old_name='batch_id',
            new_name='charge_request_batch_id',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='batch_request_response',
        ),
        migrations.AddField(
            model_name='payment',
            name='charge_request_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='charge_request_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pre_auth_confirmation_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='charge_request_get_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='charge_request_response',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='pre_auth_batch_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='pre_auth_get_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
