# Generated by Django 3.1.11 on 2021-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20210525_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='charge_request_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
