# Generated by Django 3.1.11 on 2021-05-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20210525_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='get_failure_log',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='post_failure_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
