# Generated by Django 3.1.11 on 2021-06-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20210525_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='charge_confirmation_request_status',
            new_name='payment_request_status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='charge_request_status',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='pre_auth_request_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='charge_request_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
