# Generated by Django 3.1.11 on 2021-06-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_auto_20210604_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_auth_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_confirm_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='RefundLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_request_response', models.JSONField(blank=True, null=True)),
                ('get_request_response', models.JSONField(blank=True, null=True)),
                ('refund_batch_id', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
        ),
    ]
