# Generated by Django 3.1.11 on 2021-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20210607_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
