# Generated by Django 3.1.11 on 2021-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_auto_20210610_1213'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(payment_status='APPROVED'), fields=('order_id',), name='Unique approved payment'),
        ),
    ]
