# Generated by Django 3.1.11 on 2021-06-18 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_refund_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='align_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='date_of_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='latest_outlet_latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='outlet',
            name='latest_outlet_longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='outlet',
            name='route_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
