# Generated by Django 3.1 on 2021-10-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0001_initial'),
        ('payments', '0031_auto_20211020_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='onboard',
            field=models.BooleanField(default=False, verbose_name='Onboarded to Kasha'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_rep.salesrep', verbose_name='Sales Rep'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='status',
            field=models.CharField(choices=[('AP', 'APPROVED'), ('PD', 'PENDING'), ('RJ', 'REJECTED')], default='PD', max_length=2, verbose_name='Status'),
        ),
    ]
