# Generated by Django 3.1 on 2021-11-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_auto_20211025_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='route_name',
        ),
        migrations.AlterField(
            model_name='outlet',
            name='outlet_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Duka's Outlet Name"),
        ),
    ]
