# Generated by Django 3.1 on 2021-11-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_auto_20211029_1041'),
        ('payments', '0033_auto_20211110_1118'),
    ]

    operations = [
    ]
