# Generated by Django 3.1 on 2021-11-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_merge_20211110_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='route_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
