# Generated by Django 3.1 on 2021-12-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_outlet_route_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'verbose_name': "Duka's Outlet", 'verbose_name_plural': "Duka's Outlets"},
        ),
    ]
