# Generated by Django 3.1 on 2022-01-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0036_auto_20211203_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_request_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pre_auth_confirmation_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pre_auth_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
