# Generated by Django 3.1 on 2021-10-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duka_zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sales Rep name')),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('jaza_duka_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='duka_zones.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'SalesRep',
                'verbose_name_plural': 'SalesReps',
            },
        ),
    ]
